ARDUINODIR:=/Applications/Arduino.marlin.app/Contents/Resources/Java
AVRTOOLSPATH := $(ARDUINODIR)/hardware/tools/avr/bin
SOURCES := Trinity.ino
LIBRARIES := SPI oled256 SD
BOARD := mighty_opt
#BOARD := atmega328
include ../../../arduino.mk
